# Site settings
title: Dinsmore Design
email: derek@dinsmore-design.com
description: > # this means to ignore newlines until "baseurl:"
  We help clients develop their brand, strengthen marketing strategies and acquire
  life-long customers through creative and visually stunning communication.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: ddinsmoredesign
facebook_url: https://www.facebook.com/ddinsmoredesign
twitter_username: dinsmoredesign
twitter_url: https://twitter.com/dinsmoredesign
instagram_username: 
instagram_url: 
dribble_username: 
dribble_url: 
github_username: DinsmoreDesign
github_url: https://github.com/DinsmoreDesign

# SEO Stuff:

facebook:
  app_id: 555404704576320
  publisher: 555404704576320
  admins: 555404704576320
logo: /images/logo.svg
google_site_verification: Je_N8gBJkCkgNH7CGBcP1Lx8GebKzVdXVQWx-KjgkmY
author:
  twitter: dinsmoredesign

# Build settings
markdown: kramdown
permalink: pretty

# paginate: 4
# paginate_path: "blog/page:num"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  # - jekyll-paginate

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/