# Site settings
title: Daralfalah
email: derek@dinsmore-design.com
description: >
  Design and Development - Built for YOU! Creating your company's website is about building your brand. We build brands for companies who want to create meaningful relationships with their clients.
lang: en-US
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dinsmoredesign.com" # the base hostname & protocol for your site
facebook_username: ddinsmoredesign
facebook_url: https://www.facebook.com/ddinsmoredesign
twitter_username: dinsmoredesign
twitter_url: https://twitter.com/dinsmoredesign
instagram_username: dinsmoredesign
instagram_url: https://www.instagram.com/dinsmoredesign
dribble_username:
dribble_url:
github_username: DinsmoreDesign
github_url: https://github.com/DinsmoreDesign
pubdate: 2016-10-05 00:00:00 -0700

# SEO Stuff:

facebook:
  # app_id: 555404704576320
  publisher: 555404704576320
  # admins: 555404704576320
twitter:
  username: dinsmoredesign
social:
  links:
    - https://www.facebook.com/ddinsmoredesign
    - https://twitter.com/dinsmoredesign
    - https://www.instagram.com/dinsmoredesign/
    - https://github.com/DinsmoreDesign
logo: /images/daralflah.png
google_site_verification: Je_N8gBJkCkgNH7CGBcP1Lx8GebKzVdXVQWx-KjgkmY
google_analytics: UA-30270281-1
author:
  twitter: dinsmoredesign

# Build settings
markdown: kramdown
permalink: pretty

# paginate: 4
# paginate_path: "blog/page:num"

# Minifier settings
minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs

gems:

  - jekyll-seo-tag
  - jekyll/minibundle
  # - jekyll-paginate
  # - jekyll-feed
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  products:
    output: true
    permalink: /products/:path/

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
